{"uuid": "be12595d-8c18-4dd9-bd5b-ce5f107658ee", "children": ["92142625-8c4d-49d9-bdda-7c02492acc9d", "0d740394-f484-4164-b1f7-6bd8551a9967"], "befores": [{"name": "setup", "status": "passed", "start": 1706443768734, "stop": 1706443781702}], "afters": [{"name": "setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=120.0.6099.227)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6EDCB2142+3514994]\n\t(No symbol) [0x00007FF6ED8D0CE2]\n\t(No symbol) [0x00007FF6ED7776AA]\n\t(No symbol) [0x00007FF6ED75E1E9]\n\t(No symbol) [0x00007FF6ED75F7CE]\n\t(No symbol) [0x00007FF6ED777CC3]\n\t(No symbol) [0x00007FF6ED750580]\n\t(No symbol) [0x00007FF6ED7F2EA1]\n\t(No symbol) [0x00007FF6ED7E5FB0]\n\t(No symbol) [0x00007FF6ED7B4BDC]\n\t(No symbol) [0x00007FF6ED7B5C64]\n\tGetHandleVerifier [0x00007FF6EDCDE16B+3695259]\n\tGetHandleVerifier [0x00007FF6EDD36737+4057191]\n\tGetHandleVerifier [0x00007FF6EDD2E4E3+4023827]\n\tGetHandleVerifier [0x00007FF6EDA004F9+689705]\n\t(No symbol) [0x00007FF6ED8DC048]\n\t(No symbol) [0x00007FF6ED8D8044]\n\t(No symbol) [0x00007FF6ED8D81C9]\n\t(No symbol) [0x00007FF6ED8C88C4]\n\tBaseThreadInitThunk [0x00007FFE92CD7344+20]\n\tRtlUserThreadStart [0x00007FFE94CC26B1+33]\n\n", "trace": "  File \"C:\\SPython_Proj\\Pytest_proj\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\SPython_Proj\\Pytest_proj\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 932, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\SPython_Proj\\Pytest_proj\\conftest.py\", line 15, in setup\n    driver.close()\n  File \"C:\\SPython_Proj\\Pytest_proj\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 459, in close\n    self.execute(Command.CLOSE)\n  File \"C:\\SPython_Proj\\Pytest_proj\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\SPython_Proj\\Pytest_proj\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1706443840173, "stop": 1706443840256}], "start": 1706443768734, "stop": 1706443840256}